name: Feature tests

on:
  workflow_dispatch:

jobs:
  feature-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:latest
            network=host

      - name: Build and run feature tests
        env:
          DOCKER_BUILDKIT: 1
          COMPOSE_DOCKER_CLI_BUILD: 1
          BUILDX_CACHE_FROM: type=gha
          BUILDX_CACHE_TO: type=gha,mode=max
        run: |
          mkdir -p artifacts
          make behave
      - name: Save Docker logs
        if: failure()
        run: docker compose logs --no-color > artifacts/docker-compose.log

      - name: Upload artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: failure-logs
          path: artifacts

      - name: Teardown
        if: always()
        run: |
          docker compose -f docker-compose.yml -f docker-compose.feature-tests.yml down -v
