name: Integration tests

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: webcaf
          POSTGRES_USER: webcaf
          POSTGRES_PASSWORD: webcaf
        ports:
          - "5432:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Install pyenv and Python
        run: |
          curl https://pyenv.run | bash && \
          export PYENV_ROOT="$HOME/.pyenv" && \
          [[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH" && \
          eval "$(pyenv init -)" && \
          for repo in ~/.pyenv/plugins/*/ ~/.pyenv/; do [[ -d "$repo/.git" ]] && (cd "$repo" && git remote set-head origin -a); done && \
          pyenv update && \
          pyenv install 3.12 && \
          pyenv global 3.12 && \
          pyenv rehash
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade poetry pre-commit
          poetry install --no-root
      - name: Run linters
        run: |
          pre-commit run --all
      - name: Init server
        env:
          SECRET_KEY: blah
          DATABASE_URL: postgresql://webcaf:webcaf@localhost:5432/webcaf
          DOMAIN_NAME: http://localhost:8010
          SSO_MODE: localhost
        run: |
          poetry run ./manage.py collectstatic --noinput
          poetry run ./manage.py migrate --noinput
      - name: Start Dex container
        run: |
          docker run -d \
            --name dex \
            --volume ${{ github.workspace }}/oauth-stub:/etc/dex \
            -p 5556:5556 \
            ghcr.io/dexidp/dex:v2.37.0 \
            dex serve /etc/dex/config.yaml
      - name: Wait for Dex to be ready
        run: |
          echo "Waiting for Dex..."
          for i in {1..30}; do
          if curl -sSf http://localhost:5556/.well-known/openid-configuration > /dev/null; then
          echo "Dex is ready."
          break
          else
          echo "Dex not ready yet ($i)..."
          sleep 2
          fi
          done
          docker logs dex || true
      - name: Run Unit Tests
        env:
          DATABASE_URL: postgresql://webcaf:webcaf@localhost:5432/webcaf
          AWS_ENDPOINT_URL_S3: http://127.0.0.1:9090
          CLAMD_TCP_ADDR: 127.0.0.1
          S3_STORAGE_ENABLED: "True"
          AWS_ACCESS_KEY_ID: "dummy-key-id"
          AWS_SECRET_ACCESS_KEY: "dummy-key"
          ENVIRONMENT: 'local'
          SSO_MODE: localhost
        run: |
          SECRET_KEY=unneeded DOMAIN_NAME=http://localhost:8010 poetry run python manage.py test -v 2
